import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Link } from 'react-router-dom';
import {
  ChevronLeft, CheckCircle, XCircle, AlertCircle, FileText, MessageSquare,
  User, Shield, ChevronDown, ChevronUp, ExternalLink, Search, Filter
} from 'lucide-react';

// ── Page registry ─────────────────────────────────────────────────────────────
const PAGES = [
  // Public / Landing
  { id: 'thebridge', label: 'The Bridge Master Site', path: '/thebridge', section: 'Public', navDir: 'Direct URL — not in sidebar', userAccess: true, adminOnly: false, userDesc: 'The public-facing product landing page. Visitors see Pocket Pal cards, app suite overview, and can sign up.', adminDesc: 'No admin-specific tools. Edit Pocket Pal content in code.' },
  { id: 'landing', label: 'Landing / Funnel', path: '/landing', section: 'Public', navDir: 'Direct URL or after logout', userAccess: true, adminOnly: false, userDesc: 'User selects their journey — Academy or Trading Platform. Routes to onboarding.', adminDesc: 'Controls which path new users take. Edit segments in code.' },
  { id: 'academy-store', label: 'Academy Store', path: '/academy-store', section: 'Public', navDir: 'Header link / Store button', userAccess: true, adminOnly: false, userDesc: 'Users browse and purchase courses, memberships, bot rentals, and Companion Creator packs.', adminDesc: 'Admin can edit Specials board and Tip Jar via the gear icon (⚙) on that page.' },

  // App (requires login)
  { id: 'dashboard', label: 'Dashboard', path: '/', section: 'App', navDir: 'Sidebar → Home icon', userAccess: true, adminOnly: false, userDesc: 'Main hub showing portfolio, bot command center, signals, and quick actions.', adminDesc: 'Admin sees extra overlays and floating admin toggle.' },
  { id: 'signals', label: 'Signals', path: '/signals', section: 'App', navDir: 'Sidebar → Signals', userAccess: true, adminOnly: false, userDesc: 'Live market signal feed with confidence ratings and asset class filters.', adminDesc: 'Signals are generated by crypto sentiment function.' },
  { id: 'paper-trading', label: 'Paper Trading', path: '/paper-trading', section: 'App', navDir: 'Sidebar → Paper Trading', userAccess: true, adminOnly: false, userDesc: 'Virtual $100k portfolio. Enter/exit trades, view P&L, mirror others, journal entries.', adminDesc: 'All trades are virtual. No real money is involved.' },
  { id: 'bot-rental', label: 'Bot Rental', path: '/bot-rental', section: 'App', navDir: 'Sidebar → Bot Rental', userAccess: true, adminOnly: false, userDesc: 'Browse and rent AI faculty bots. Locked by membership tier.', adminDesc: 'Bot rental slots are set per MembershipTier entity.' },
  { id: 'academy-hub', label: 'Academy Hub', path: '/academy-hub', section: 'App', navDir: 'Sidebar → Education → Academy', userAccess: true, adminOnly: false, userDesc: 'Full curriculum dashboard. Track progress, complete lessons, earn badges.', adminDesc: 'Lessons are managed via AcademyCommand.' },
  { id: 'office-hours', label: 'Office Hours', path: '/office-hours', section: 'App', navDir: 'Sidebar → My Mentors → Office Hours', userAccess: true, adminOnly: false, userDesc: 'Live AI chat with any faculty persona. Voice-enabled.', adminDesc: 'Persona content controlled by BotPersona entity.' },
  { id: 'leaderboard', label: 'Leaderboard', path: '/leaderboard', section: 'App', navDir: 'Sidebar → Leaderboard', userAccess: true, adminOnly: false, userDesc: 'Trader rankings, badge showcase, sentiment news feed.', adminDesc: 'Rankings pull from TraderRanking entity.' },
  { id: 'community', label: 'Community', path: '/community', section: 'App', navDir: 'Sidebar → Community', userAccess: true, adminOnly: false, userDesc: 'Social trading feed, shared strategies, activity stream.', adminDesc: 'Moderated by ModerationRecord entity.' },
  { id: 'settings', label: 'Settings', path: '/settings', section: 'App', navDir: 'Sidebar → Settings (bottom)', userAccess: true, adminOnly: false, userDesc: 'Profile, kill switch, benefactor form, 2FA, notification prefs.', adminDesc: 'Kill switch and benefactor settings are legally enforced.' },

  // Academy Production (admin)
  { id: 'mission-control', label: 'Mission Control', path: '/mission-control', section: 'Production', navDir: 'Direct URL or Directors Cut → Mission Control', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Central production console. All creative tools accessible from here.' },
  { id: 'directors-cut', label: "Director's Cut Hub", path: '/directors-cut', section: 'Production', navDir: 'Direct URL — admin only', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'All production tool links. Launch pad for the creative suite.' },
  { id: 'scene-studio', label: 'Scene Studio', path: '/scene-studio', section: 'Production', navDir: 'Mission Control → Scene Production', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Build animated scenes with beat machine, characters, scripts, FX.' },
  { id: 'scene-sandbox', label: 'Scene Sandbox', path: '/scene-sandbox', section: 'Production', navDir: 'Mission Control → Scene Production → Scene Sandbox', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Drag characters + dialogue → render low-res preview with DALL-E + Azure TTS.' },
  { id: 'voice-cloning-lab', label: 'Voice Cloning Lab', path: '/voice-cloning-lab', section: 'Production', navDir: 'Mission Control → Character Voices → Voice Cloning Lab', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Upload audio samples per faculty character, clone voice via ElevenLabs, adjust & preview.' },
  { id: 'production-metrics', label: 'Production Metrics', path: '/production-metrics', section: 'Production', navDir: 'Mission Control → Audio & FX → Production Metrics', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Live scene count, compute cost, pending assets, FX plugin breakdown.' },
  { id: 'render-pipeline', label: 'Render Pipeline', path: '/render-pipeline', section: 'Production', navDir: 'Mission Control → Character Voices', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'DALL-E 3 batch render for faculty frames.' },
  { id: 'character-profiles', label: 'Character Profiles', path: '/character-profiles', section: 'Production', navDir: 'Mission Control → Character Control', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: '18 faculty dossiers with full attribute management.' },
  { id: 'academy-command', label: 'Academy Command', path: '/academy-command', section: 'Production', navDir: 'Direct URL — admin only', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Lesson management, faculty status, quest tracking.' },
  { id: 'lesson-generator', label: 'Lesson Generator', path: '/lesson-generator', section: 'Production', navDir: 'Mission Control → Audio & FX', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'AI-generated full lesson scripts with faculty dialogue.' },
  { id: 'sovereign-log', label: 'Sovereign Log', path: '/sovereign-log', section: 'Production', navDir: 'Direct URL — founder access only', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Immutable audit log of all destructive or sensitive admin actions.' },
  { id: 'scope-testing', label: 'Scope Testing', path: '/scope-testing', section: 'Production', navDir: 'Direct URL — admin/testers only', userAccess: false, adminOnly: true, userDesc: 'Testers access via invite link. Submit bug findings.', adminDesc: 'Manage test scopes, view findings, set priorities.' },

  // Utility
  { id: 'device-mockup', label: 'Device Mockup Viewer', path: '/device-mockup', section: 'Tools', navDir: 'Mission Control → coming soon', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Phone/tablet preview of Pocket Pals with quick+full descriptions.' },
  { id: 'theme-switcher', label: 'Theme Switcher', path: '/theme-switcher', section: 'Tools', navDir: 'Mission Control → coming soon', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Preview and apply different layout themes per page section.' },
  { id: 'page-index', label: 'Page Index', path: '/page-index', section: 'Tools', navDir: 'You are here', userAccess: false, adminOnly: true, userDesc: 'Not visible to regular users.', adminDesc: 'Master checklist of all pages with edit status, notes, and navigation directions.' },
  { id: 'terms', label: 'Terms & Conditions', path: '/terms', section: 'Legal', navDir: 'Footer link on Landing/Store', userAccess: true, adminOnly: false, userDesc: 'Legal agreement users must accept before using paid features.', adminDesc: 'Update in code — Terms.jsx.' },
];

const SECTIONS = ['All', 'Public', 'App', 'Production', 'Tools', 'Legal'];

const STATUS_OPTIONS = [
  { value: 'done', label: 'Done', icon: CheckCircle, color: '#00d4aa' },
  { value: 'not_needed', label: 'Not Needed', icon: XCircle, color: '#475569' },
  { value: 'needs_edit', label: 'Needs Edit', icon: AlertCircle, color: '#f59e0b' },
];

const STORAGE_KEY = 'iint_page_index_v1';

function loadNotes() {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || '{}'); } catch { return {}; }
}
function saveNotes(data) {
  try { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); } catch {}
}

export default function PageIndex() {
  const [section, setSection] = useState('All');
  const [search, setSearch] = useState('');
  const [notes, setNotes] = useState(loadNotes);
  const [expanded, setExpanded] = useState({});

  const updateNote = (pageId, patch) => {
    setNotes(prev => {
      const updated = { ...prev, [pageId]: { ...(prev[pageId] || {}), ...patch } };
      saveNotes(updated);
      return updated;
    });
  };

  const toggleExpand = (id) => setExpanded(prev => ({ ...prev, [id]: !prev[id] }));

  const filtered = PAGES.filter(p => {
    const secMatch = section === 'All' || p.section === section;
    const searchMatch = !search || p.label.toLowerCase().includes(search.toLowerCase()) || p.path.includes(search.toLowerCase());
    return secMatch && searchMatch;
  });

  const sectionGroups = SECTIONS.slice(1).map(s => ({
    name: s,
    pages: PAGES.filter(p => p.section === s),
    done: PAGES.filter(p => p.section === s && notes[p.id]?.status === 'done').length,
  }));

  return (
    <div className="min-h-screen bg-[#030508] text-[#f1f5f9]">
      {/* Header */}
      <div className="border-b border-[#a78bfa]/20 px-6 py-3 flex items-center gap-3 bg-[#030508]/95 backdrop-blur-sm sticky top-0 z-20">
        <Link to="/mission-control" className="w-7 h-7 rounded-lg bg-[#110d1f] border border-[#a78bfa]/30 flex items-center justify-center">
          <ChevronLeft size={13} className="text-[#a78bfa]" />
        </Link>
        <div>
          <p className="text-[10px] font-mono text-[#a78bfa] uppercase tracking-[0.3em]">IINT // PAGE INDEX</p>
          <p className="text-[8px] text-[#475569] font-mono">Edit checklist · Navigation guide · User vs Admin access</p>
        </div>
        <div className="ml-auto text-[9px] font-mono text-[#334155]">
          {PAGES.filter(p => notes[p.id]?.status === 'done').length}/{PAGES.length} done
        </div>
      </div>

      {/* Progress summary */}
      <div className="border-b border-[#1e293b] bg-[#070b14] px-6 py-3">
        <div className="max-w-5xl mx-auto flex flex-wrap gap-4">
          {sectionGroups.map(g => (
            <div key={g.name} className="flex items-center gap-2">
              <span className="text-[9px] font-mono text-[#475569]">{g.name}</span>
              <div className="flex gap-0.5">
                {g.pages.map(p => (
                  <div key={p.id} className="w-3 h-3 rounded-sm transition-all"
                    style={{
                      background: notes[p.id]?.status === 'done' ? '#00d4aa' :
                        notes[p.id]?.status === 'not_needed' ? '#334155' :
                          notes[p.id]?.status === 'needs_edit' ? '#f59e0b' : '#1e293b',
                    }}
                    title={p.label}
                  />
                ))}
              </div>
              <span className="text-[8px] text-[#334155]">{g.done}/{g.pages.length}</span>
            </div>
          ))}
        </div>
      </div>

      <div className="max-w-5xl mx-auto p-6 space-y-5">
        {/* Search + filter */}
        <div className="flex flex-wrap gap-2">
          <div className="relative flex-1 min-w-[180px]">
            <Search size={12} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#475569]" />
            <input value={search} onChange={e => setSearch(e.target.value)}
              placeholder="Search pages..."
              className="w-full bg-[#111827] border border-[#1e293b] rounded-xl pl-8 pr-3 py-2 text-xs text-[#f1f5f9] focus:outline-none focus:border-[#a78bfa]/50" />
          </div>
          <div className="flex gap-1 flex-wrap">
            {SECTIONS.map(s => (
              <button key={s} onClick={() => setSection(s)}
                className="px-3 py-1.5 rounded-lg text-[10px] font-bold border transition-all"
                style={{
                  borderColor: section === s ? '#a78bfa60' : '#1e293b',
                  background: section === s ? '#a78bfa15' : '#070b14',
                  color: section === s ? '#a78bfa' : '#475569',
                }}>
                {s}
              </button>
            ))}
          </div>
        </div>

        {/* Page cards */}
        <div className="space-y-2">
          {filtered.map(page => {
            const pageNote = notes[page.id] || {};
            const status = pageNote.status;
            const isExpanded = expanded[page.id];
            const statusInfo = STATUS_OPTIONS.find(s => s.value === status);

            return (
              <div key={page.id} className="rounded-2xl border overflow-hidden transition-all"
                style={{
                  borderColor: status === 'done' ? '#00d4aa25' : status === 'needs_edit' ? '#f59e0b25' : status === 'not_needed' ? '#33415525' : '#1e293b',
                  background: '#070b14',
                }}>
                {/* Row header */}
                <div className="flex items-center gap-3 px-4 py-3">
                  {/* Status dots */}
                  <div className="flex gap-1 shrink-0">
                    {STATUS_OPTIONS.map(s => {
                      const SIcon = s.icon;
                      return (
                        <button key={s.value} onClick={() => updateNote(page.id, { status: status === s.value ? null : s.value })}
                          title={s.label}
                          className="w-6 h-6 rounded-lg flex items-center justify-center transition-all"
                          style={{ background: status === s.value ? `${s.color}20` : '#111827', border: `1px solid ${status === s.value ? s.color + '50' : '#1e293b'}` }}>
                          <SIcon size={11} style={{ color: status === s.value ? s.color : '#334155' }} />
                        </button>
                      );
                    })}
                  </div>

                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <p className="text-xs font-bold text-[#f1f5f9] leading-none">{page.label}</p>
                      <span className="text-[8px] font-mono text-[#334155] px-1.5 py-0.5 rounded bg-[#111827]">{page.section}</span>
                      {page.adminOnly && (
                        <span className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-[#ef4444]/10 text-[#ef4444] border border-[#ef4444]/20">ADMIN</span>
                      )}
                      {page.userAccess && !page.adminOnly && (
                        <span className="text-[8px] font-mono px-1.5 py-0.5 rounded bg-[#00d4aa]/10 text-[#00d4aa] border border-[#00d4aa]/20">PUBLIC</span>
                      )}
                    </div>
                    <p className="text-[9px] font-mono text-[#334155] mt-0.5">{page.path}</p>
                  </div>

                  <div className="flex items-center gap-2 shrink-0">
                    <Link to={page.path} target="_blank"
                      className="w-7 h-7 rounded-lg bg-[#111827] border border-[#1e293b] flex items-center justify-center hover:border-[#334155]"
                      title="Open page">
                      <ExternalLink size={11} className="text-[#475569]" />
                    </Link>
                    <button onClick={() => toggleExpand(page.id)}
                      className="w-7 h-7 rounded-lg bg-[#111827] border border-[#1e293b] flex items-center justify-center hover:border-[#334155]">
                      {isExpanded ? <ChevronUp size={11} className="text-[#475569]" /> : <ChevronDown size={11} className="text-[#475569]" />}
                    </button>
                  </div>
                </div>

                {/* Expanded detail */}
                <AnimatePresence>
                  {isExpanded && (
                    <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }}
                      className="overflow-hidden">
                      <div className="px-4 pb-4 pt-1 space-y-3 border-t border-[#1e293b]">
                        {/* Navigation directions */}
                        <div className="flex items-start gap-2">
                          <FileText size={11} className="text-[#a78bfa] shrink-0 mt-0.5" />
                          <div>
                            <p className="text-[9px] font-mono text-[#475569] uppercase tracking-widest">How to navigate there</p>
                            <p className="text-[11px] text-[#94a3b8] mt-0.5">{page.navDir}</p>
                          </div>
                        </div>

                        {/* User access description */}
                        <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
                          <div className="p-3 rounded-xl bg-[#00d4aa]/08 border border-[#00d4aa]/15 space-y-1">
                            <div className="flex items-center gap-1.5">
                              <User size={10} className="text-[#00d4aa]" />
                              <p className="text-[9px] font-mono text-[#00d4aa] uppercase tracking-widest">What Users Can Do</p>
                            </div>
                            <p className="text-[10px] text-[#64748b] leading-relaxed">{page.userDesc}</p>
                          </div>
                          <div className="p-3 rounded-xl bg-[#ef4444]/08 border border-[#ef4444]/15 space-y-1">
                            <div className="flex items-center gap-1.5">
                              <Shield size={10} className="text-[#ef4444]" />
                              <p className="text-[9px] font-mono text-[#ef4444] uppercase tracking-widest">Admin Notes</p>
                            </div>
                            <p className="text-[10px] text-[#64748b] leading-relaxed">{page.adminDesc}</p>
                          </div>
                        </div>

                        {/* Notes textarea */}
                        <div className="space-y-1.5">
                          <div className="flex items-center gap-1.5">
                            <MessageSquare size={10} className="text-[#475569]" />
                            <p className="text-[9px] font-mono text-[#475569] uppercase tracking-widest">Change Notes / To-Do</p>
                          </div>
                          <textarea
                            value={pageNote.note || ''}
                            onChange={e => updateNote(page.id, { note: e.target.value })}
                            placeholder="Add notes about what needs changing, what was edited, or ideas..."
                            rows={2}
                            className="w-full bg-[#111827] border border-[#1e293b] rounded-xl px-3 py-2 text-[11px] text-[#f1f5f9] resize-none focus:outline-none focus:border-[#a78bfa]/50"
                          />
                        </div>

                        {/* Status selector */}
                        <div className="flex items-center gap-2">
                          <p className="text-[9px] font-mono text-[#334155]">Status:</p>
                          {STATUS_OPTIONS.map(s => {
                            const SIcon = s.icon;
                            return (
                              <button key={s.value} onClick={() => updateNote(page.id, { status: status === s.value ? null : s.value })}
                                className="flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-[10px] font-bold border transition-all"
                                style={{
                                  borderColor: status === s.value ? `${s.color}50` : '#1e293b',
                                  background: status === s.value ? `${s.color}15` : '#111827',
                                  color: status === s.value ? s.color : '#475569',
                                }}>
                                <SIcon size={10} /> {s.label}
                              </button>
                            );
                          })}
                        </div>
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            );
          })}
        </div>
      </div>
    </div>
  );
}