import React, { useState } from 'react';
import { Download, Loader2 } from 'lucide-react';
import { jsPDF } from 'jspdf';

// Branded IINT PDF generator — no external deps beyond jsPDF (already installed)

function drawBrandHeader(doc, pageW) {
  // Dark header band
  doc.setFillColor(7, 11, 20);
  doc.rect(0, 0, pageW, 28, 'F');

  // Teal accent line
  doc.setFillColor(0, 212, 170);
  doc.rect(0, 28, pageW, 2, 'F');

  // Logo text
  doc.setTextColor(0, 212, 170);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text('IINT', 14, 18);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.text('Intelligence · Institute · Neural · Trading', 36, 15);
  doc.text('Beta v0.1.0 — Confidential', 36, 21);
}

function drawBrandFooter(doc, pageW, pageH, pageNum, total) {
  doc.setFillColor(17, 24, 39);
  doc.rect(0, pageH - 16, pageW, 16, 'F');
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by IINT Platform · For personal record keeping only · Not financial advice', 14, pageH - 5);
  doc.text(`Page ${pageNum} of ${total}`, pageW - 14, pageH - 5, { align: 'right' });
}

function sectionTitle(doc, text, y, pageW) {
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, pageW - 28, 8, 'F');
  doc.setTextColor(0, 212, 170);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'bold');
  doc.text(text.toUpperCase(), 17, y + 5.5);
  return y + 12;
}

export function exportJournalEntryPDF(entry) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(7, 11, 20);
  doc.rect(0, 0, pageW, pageH, 'F');

  drawBrandHeader(doc, pageW);

  // Title
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('Trade Journal Entry', 14, 44);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const dateStr = entry.created_date
    ? new Date(entry.created_date).toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })
    : new Date().toLocaleString();
  doc.text(dateStr, 14, 51);

  let y = 62;

  // Trade snapshot card
  y = sectionTitle(doc, 'Trade Summary', y, pageW);
  const fields = [
    ['Ticker', entry.ticker || '—'],
    ['Direction', (entry.trade_type || '—').toUpperCase()],
    ['Entry Price', entry.entry_price ? `$${Number(entry.entry_price).toLocaleString()}` : '—'],
    ['P&L', entry.pnl !== undefined ? `${entry.pnl >= 0 ? '+' : ''}$${Number(entry.pnl).toFixed(2)}` : '—'],
    ['P&L %', entry.pnl_percent !== undefined ? `${Number(entry.pnl_percent).toFixed(2)}%` : '—'],
  ];
  fields.forEach(([label, val], i) => {
    const col = i % 2 === 0 ? 14 : pageW / 2 + 7;
    const row = y + Math.floor(i / 2) * 10;
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.text(label, col, row);
    doc.setTextColor(241, 245, 249);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.text(val, col, row + 5);
  });
  y += Math.ceil(fields.length / 2) * 10 + 8;

  // Emotion + tag
  y = sectionTitle(doc, 'Psychology', y, pageW);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'normal');
  doc.text('Emotion', 14, y);
  doc.text('Lesson Tag', pageW / 2 + 7, y);
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'bold');
  doc.text(entry.emotion || '—', 14, y + 6);
  doc.text((entry.lesson_tag || '—').replace(/_/g, ' '), pageW / 2 + 7, y + 6);
  y += 18;

  // Reflection note
  y = sectionTitle(doc, 'Reflection Note', y, pageW);
  doc.setTextColor(148, 163, 184);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  const noteLines = doc.splitTextToSize(entry.note || 'No note recorded.', pageW - 28);
  doc.text(noteLines, 14, y);
  y += noteLines.length * 5 + 10;

  // Accent divider
  doc.setFillColor(0, 212, 170);
  doc.rect(14, y, 40, 1, 'F');

  drawBrandFooter(doc, pageW, pageH, 1, 1);

  doc.save(`IINT_Journal_${entry.ticker || 'entry'}_${Date.now()}.pdf`);
}

export function exportPortfolioPDF(positions, journalEntries = []) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  doc.setFillColor(7, 11, 20);
  doc.rect(0, 0, pageW, pageH, 'F');
  drawBrandHeader(doc, pageW);

  // Title
  doc.setTextColor(241, 245, 249);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Portfolio Performance Report', 14, 44);
  doc.setTextColor(100, 116, 139);
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.text(`Generated: ${new Date().toLocaleString('en-US', { dateStyle: 'full', timeStyle: 'short' })}`, 14, 51);

  let y = 62;

  // Summary metrics
  const totalPnl = positions.reduce((s, p) => s + (p.pnl || 0), 0);
  const openPos = positions.filter(p => p.status === 'open').length;
  const closedPos = positions.filter(p => p.status === 'closed').length;
  const winners = positions.filter(p => (p.pnl || 0) > 0).length;
  const winRate = positions.length > 0 ? ((winners / positions.length) * 100).toFixed(1) : '0.0';

  y = sectionTitle(doc, 'Portfolio Summary', y, pageW);
  const summaryMetrics = [
    ['Virtual Balance', '$100,000.00'],
    ['Total P&L', `${totalPnl >= 0 ? '+' : ''}$${totalPnl.toFixed(2)}`],
    ['Open Positions', String(openPos)],
    ['Closed Trades', String(closedPos)],
    ['Win Rate', `${winRate}%`],
    ['Journal Entries', String(journalEntries.length)],
  ];
  summaryMetrics.forEach(([label, val], i) => {
    const col = i % 2 === 0 ? 14 : pageW / 2 + 7;
    const row = y + Math.floor(i / 2) * 11;
    doc.setTextColor(100, 116, 139);
    doc.setFontSize(7.5);
    doc.setFont('helvetica', 'normal');
    doc.text(label, col, row);
    const isPositive = val.startsWith('+');
    const isNegative = val.startsWith('-$') && label === 'Total P&L';
    doc.setTextColor(isPositive ? 0 : isNegative ? 239 : 241, isPositive ? 212 : isNegative ? 68 : 245, isPositive ? 170 : isNegative ? 68 : 249);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text(val, col, row + 6);
  });
  y += Math.ceil(summaryMetrics.length / 2) * 11 + 8;

  // Positions table
  y = sectionTitle(doc, 'All Positions', y, pageW);
  const headers = ['Ticker', 'Direction', 'Qty', 'Entry', 'P&L', 'Status'];
  const colW = [(pageW - 28) / 6, (pageW - 28) / 6, (pageW - 28) / 8, (pageW - 28) / 5, (pageW - 28) / 5, (pageW - 28) / 6];
  const colX = [14];
  for (let i = 1; i < headers.length; i++) colX.push(colX[i - 1] + colW[i - 1]);

  doc.setTextColor(100, 116, 139);
  doc.setFontSize(7.5);
  doc.setFont('helvetica', 'bold');
  headers.forEach((h, i) => doc.text(h, colX[i], y));
  y += 2;
  doc.setFillColor(30, 41, 59);
  doc.rect(14, y, pageW - 28, 0.5, 'F');
  y += 4;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  positions.slice(0, 20).forEach((p) => {
    if (y > pageH - 30) {
      doc.addPage();
      doc.setFillColor(7, 11, 20);
      doc.rect(0, 0, pageW, pageH, 'F');
      y = 20;
    }
    const pnlVal = p.pnl || 0;
    const rowData = [
      p.ticker || '—',
      (p.trade_type || '').toUpperCase(),
      String(p.quantity || ''),
      p.entry_price ? `$${Number(p.entry_price).toLocaleString()}` : '—',
      `${pnlVal >= 0 ? '+' : ''}$${pnlVal.toFixed(2)}`,
      p.status || '—',
    ];
    rowData.forEach((val, i) => {
      if (i === 4) {
        doc.setTextColor(pnlVal >= 0 ? 0 : 239, pnlVal >= 0 ? 212 : 68, pnlVal >= 0 ? 170 : 68);
      } else {
        doc.setTextColor(241, 245, 249);
      }
      doc.text(val, colX[i], y);
    });
    y += 7;
  });

  drawBrandFooter(doc, pageW, pageH, 1, 1);
  doc.save(`IINT_Portfolio_Report_${Date.now()}.pdf`);
}

export default function PDFExportButton({ type = 'journal', entry = null, positions = [], journalEntries = [], className = '' }) {
  const [loading, setLoading] = useState(false);

  const handleExport = async () => {
    setLoading(true);
    await new Promise(r => setTimeout(r, 200)); // allow UI update
    if (type === 'journal' && entry) {
      exportJournalEntryPDF(entry);
    } else if (type === 'portfolio') {
      exportPortfolioPDF(positions, journalEntries);
    }
    setLoading(false);
  };

  return (
    <button
      onClick={handleExport}
      disabled={loading}
      className={`flex items-center gap-1.5 px-3 py-2 rounded-xl text-xs font-semibold border border-[#1e293b] text-[#64748b] hover:border-[#00d4aa]/40 hover:text-[#00d4aa] transition-colors disabled:opacity-40 ${className}`}
    >
      {loading ? <Loader2 size={12} className="animate-spin" /> : <Download size={12} />}
      {type === 'portfolio' ? 'Export PDF Report' : 'Export PDF'}
    </button>
  );
}